#!/usr/bin/env bash

WORKSPACES=("$HOME/Documenti/forbole"  "$HOME/Documenti/Progetti" "$HOME/Documents/forbole" "$HOME/Documents/projects")

active_icon="🟢"
inactive_icon="⚫"

function listDirectories() {
  local dirs=()
  for dir in "${WORKSPACES[@]}"; do
    dirs+=($(ls -1 "$dir"))
  done
  for dir in "${dirs[@]}"; do
    # Check if there is already a tmux session with the same name
    if tmux has-session -t "$dir" 2>/dev/null; then
      printf "$active_icon "
    else
      printf "$inactive_icon "
    fi
    echo "$dir"
  done
  echo "quit"
}

function runNeoVim() {
  local project=$1
  local is_active=$2
  for dir in "${WORKSPACES[@]}"; do
    local path="$dir/$project"
    if [ -d "$path" ]; then
      # Check if there is already a tmux session with the same name
      if [ "$is_active" == "$active_icon" ]; then
        cmd="alacritty --title $1 --working-directory=$path -e tmux attach -t $1"
      else
        cmd="alacritty --title $1 --working-directory=$path -e tmux new -s $1 nvim ."
      fi

      $cmd &>/dev/null & disown;
      break
    fi
  done
}

if [ -z "$1" ] ; then
  listDirectories
elif [ x"$@" = x"quit" ] ; then
  exit 1
else
  IFS=' ' read -r -a arguments <<< "$1"
  runNeoVim "${arguments[1]}" "${arguments[0]}"
  exit 0
fi
