" Vim configurations
" Show line numbers
set nu

" Plugins management
call plug#begin('~/.vim/plugged')

Plug 'kaicataldo/material.vim'
" Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'https://github.com/terryma/vim-multiple-cursors.git'
Plug 'https://github.com/kien/ctrlp.vim.git'

call plug#end()

" Material theme
if (has("nvim"))
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

if (has("termguicolors"))
  set termguicolors
endif

let g:material_theme_style = 'dark'

set background=dark
colorscheme material
set laststatus=2

" Mutli cursor
let g:multi_cursor_use_default_mapping=0

let g:multi_cursor_start_word_key      = '<C-d>'
let g:multi_cursor_select_all_word_key = '<A-d>'
let g:multi_cursor_start_key           = 'g<C-d>'
let g:multi_cursor_select_all_key      = 'g<A-d>'
let g:multi_cursor_next_key            = '<C-d>'
let g:multi_cursor_prev_key            = '<C-p>'
let g:multi_cursor_skip_key            = '<C-x>'
let g:multi_cursor_quit_key            = '<Esc>'

" Identation settings
syntax enable
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" Windows navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright
