# True Color Support
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Status bar position
set-option -g status-position bottom
# Main status bar colors
set-option -g status-style bg=#5b21b6,fg=#e9d5ff
# Session name in orange container with powerline arrow
# set-option -g status-left "#[bg=#FF9300,fg=#0a0014,bold]#S#[bg=#5b21b6]#[fg=#FF9300]\ue0bc"
set-option -g status-left "#{?client_prefix,#[bg=#AD3D6F fg=#e9d5ff],#[bg=#FF9300 fg=#0A0014]}#[bold] #S #[bg=#5b21b6]#{?client_prefix,#[fg=#AD3D6F],#[fg=#FF9300]}\ue0bc"

# Empty right side for now
set-option -g status-right ""

# Increase status length
set-option -g status-left-length 100

# Status bar refresh interval
set-option -g status-interval 5

# Windows style
set-option -g window-status-style bg=#5b21b6,fg=#e9d5ff
set-option -g window-status-current-format "#[bg=#8b5cf6,fg=#5b21b6]\ue0bc#[bg=#8b5cf6,fg=#e9d5ff,bold] #I:#W #[bg=#5b21b6,fg=#8b5cf6]\ue0bc"
set-option -g window-status-format "#[bg=#3d1a5f]#[fg=#5b21b6]\ue0bc #[fg=#AD3D6F]#I:#W #[bg=#5b21b6]#[fg=#3d1a5f]\ue0bc"
set-option -g window-status-separator ""

# Add git branch on the right side with styling
set-option -g status-right "#[fg=#5b21b6,bg=#AD3D6F]\ue0bc#[fg=#e9d5ff,bold] \uE0A0 #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null) "

# Increase right status length to fit branch names
set-option -g status-right-length 50
